INSERT INTO [category] (name) VALUES (N'Data Science');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (1, N'Data Analysis');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (1, N'Data Analytics');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (1, N'Data Visualization');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (1, N'Data Mining');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (1, N'Data Engineering');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (1, N'Data Science');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (1, N'Data Privacy');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (1, N'Data Governance');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (1, N'Data Warehousing');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (1, N'Health Data Analysis');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (1, N'Environmental Data Analysis');
INSERT INTO [category] (name) VALUES (N'Machine Learning & AI');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (2, N'Machine Learning');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (2, N'Artificial Intelligence');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (2, N'Deep Learning');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (2, N'Predictive Analytics');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (2, N'Reinforcement Learning');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (2, N'Artificial Neural Networks');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (2, N'Genetic Algorithms');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (2, N'Fuzzy Logic');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (2, N'AI-driven Decision Making');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (2, N'AI in Healthcare');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (2, N'Ethical AI Practices');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (2, N'Advanced Computational Techniques');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (2, N'AI in Robotics');
INSERT INTO [category] (name) VALUES (N'Cloud Computing & IoT');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (3, N'Cloud Computing');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (3, N'Cloud Security');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (3, N'Cloud Storage Solutions');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (3, N'IoT Security');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (3, N'IoT Applications');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (3, N'Smart Cities');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (3, N'Smart Technologies');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (3, N'Virtualization Technologies');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (3, N'Real-Time Data Processing');
INSERT INTO [category] (name) VALUES (N'Cybersecurity');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (4, N'Bioinformatics');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (4, N'Cybersecurity');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (4, N'Ethical Hacking');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (4, N'Network Security');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (4, N'Database Security');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (4, N'Information Retrieval');
INSERT INTO [category] (name) VALUES (N'Data Engineering & Analytics');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (5, N'Spatial Data Analysis');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (5, N'Big Data');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (5, N'Predictive Modeling');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (5, N'Statistical Methods');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (5, N'Quantitative Analysis');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (5, N'Business Intelligence');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (5, N'Financial Analytics');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (5, N'Financial Modeling');
INSERT INTO [category] (name) VALUES (N'Software Development & Programming');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (6, N'Augmented Reality');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (6, N'Virtual Reality');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (6, N'Blockchain');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (6, N'Software Development');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (6, N'Programming');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (6, N'Advanced Programming');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (6, N'Algorithm Design');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (6, N'Optimization');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (6, N'Optimization Techniques');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (6, N'Text Mining');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (6, N'Time Series Analysis');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (6, N'Machine Vision');
INSERT INTO [category] (name) VALUES (N'Networking & Systems');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (7, N'Networking');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (7, N'Systems Analysis');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (7, N'IT Infrastructure');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (7, N'System Integration');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (7, N'Database Management');
INSERT INTO [category] (name) VALUES (N'Business & Management');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (8, N'Business Analysis');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (8, N'Project Management');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (8, N'Supply Chain Management');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (8, N'Business Process Management');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (8, N'Customer Relationship Management');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (8, N'Logistics Management');
INSERT INTO [category] (name) VALUES (N'Economics');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (9, N'Retail Analytics');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (9, N'Content Management Systems');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (9, N'Digital Marketing');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (9, N'E-commerce Analytics');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (9, N'Economic Theory');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (9, N'Macroeconomics');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (9, N'Microeconomics');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (9, N'Development Economics');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (9, N'Behavioral Economics');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (9, N'International Trade');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (9, N'Financial Economics');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (9, N'Public Economics');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (9, N'Labor Economics');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (9, N'Environmental Economics');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (9, N'Econometrics');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (9, N'Industrial Organization');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (9, N'Health Economics');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (9, N'Agricultural Economics');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (9, N'Urban Economics');
INSERT INTO [category] (name) VALUES (N'Sociology');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (10, N'Sentiment Analysis');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (10, N'Social Network Analysis');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (10, N'Social Theory');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (10, N'Sociological Research Methods');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (10, N'Cultural Sociology');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (10, N'Urban Sociology');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (10, N'Criminal Sociology');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (10, N'Political Sociology');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (10, N'Social Stratification');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (10, N'Gender Studies');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (10, N'Family Sociology');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (10, N'Sociology of Education');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (10, N'Globalization Studies');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (10, N'Social Change');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (10, N'Ethnography');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (10, N'Social Networks');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (10, N'Deviance and Social Control');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (10, N'Social Policy');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (10, N'Migration Studies');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (10, N'Social Movements');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (10, N'Economic Sociology');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (10, N'Social Psychology');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (10, N'Sociology of Religion');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (10, N'Social Inequality');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (10, N'Community Studies');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (10, N'Health and Society');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (10, N'Social Impact Assessment');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (10, N'Sociology of Work');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (10, N'Race and Ethnicity Studies');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (10, N'Social Capital');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (10, N'Digital Sociology');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (10, N'Sociology of the Family');
INSERT INTO [category] (name) VALUES (N'Education');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (11, N'Educational Data Mining');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (11, N'Educational Psychology');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (11, N'Curriculum Development');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (11, N'Instructional Design');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (11, N'Pedagogical Methods');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (11, N'Education Policy');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (11, N'Higher Education');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (11, N'Early Childhood Education');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (11, N'Special Education');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (11, N'Adult Education');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (11, N'Educational Leadership');
INSERT INTO [category] (name) VALUES (N'Health and Wellness');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (12, N'Public Health');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (12, N'Epidemiology');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (12, N'Health Policy');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (12, N'Global Health');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (12, N'Mental Health');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (12, N'Healthcare Management');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (12, N'Health Promotion');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (12, N'Nutrition and Wellness');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (12, N'Healthcare Ethics');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (12, N'Pharmaceutical Sciences');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (12, N'Health Informatics');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (12, N'Clinical Research');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (12, N'Healthcare Technology');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (12, N'Medical Sociology');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (12, N'Rehabilitation Sciences');
INSERT INTO [category] (name) VALUES (N'Environmental Science');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (13, N'Energy Management');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (13, N'Agricultural Analytics');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (13, N'Environmental Science');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (13, N'Climate Change');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (13, N'Sustainability Studies');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (13, N'Ecology');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (13, N'Environmental Policy');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (13, N'Renewable Energy');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (13, N'Natural Resource Management');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (13, N'Conservation Biology');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (13, N'Marine Biology');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (13, N'Urban Ecology');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (13, N'Environmental Chemistry');
INSERT INTO [category] (name) VALUES (N'Psychology');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (14, N'Cognitive Psychology');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (14, N'Developmental Psychology');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (14, N'Clinical Psychology');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (14, N'Behavioral Psychology');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (14, N'Neuroscience');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (14, N'Psychological Assessment');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (14, N'Psychotherapy');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (14, N'Forensic Psychology');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (14, N'Health Psychology');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (14, N'Positive Psychology');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (14, N'Industrial-Organizational Psychology');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (14, N'Personality Psychology');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (14, N'Sports Psychology');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (14, N'Counseling Psychology');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (14, N'Abnormal Psychology');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (14, N'Experimental Psychology');
INSERT INTO [subCategory] (parentCategoryId, name) VALUES (14, N'Environmental Psychology');
GO
